Sample file as below.
 
sonar.verbose=true
sonar.organization=FQTS
sonar.projectKey=fqts-key1_project2-trend-tweet
sonar.projectName=Project2-trend-tweet
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml